-- Kör filen i Supabase: SQL Editor > New query > Run.
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  name text not null check (name in ('page_view', 'booking_click', 'contact_click')),
  path text not null check (char_length(path) between 1 and 140),
  source text not null check (char_length(source) between 1 and 140),
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);

create index if not exists analytics_events_name_idx
  on public.analytics_events (name);

alter table public.analytics_events enable row level security;

-- Inga policies skapas. Därmed kan anon/authenticated inte läsa eller skriva.
-- Webbservern använder service_role på serversidan och kan fortfarande komma åt tabellen.
